### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by Gapstare** [tenox7/wrp#41] opened 2019-06-06 15:17 UTC
I tried wrp 3.0 beta on Raspberry Pi 3 (Raspbian Stretch) and when idle wrp uses about 10% cpu. Is there anything that can be done to lower this?

Great program by the way :)

**Comment by tenox7** [comment] 2019-06-06 19:40
Thank you for reporting. Interesting! I will look in to that!

**Comment by tenox7** [comment] 2019-06-07 07:29
ack I was able to reproduce it and not only on rpi, the issue is that chromecdp is continuously communicating with chrome browser in the background, I will open an upstream issue about this, as a workaround perhaps one browser instance could be spawned and closed per request... let me see what can be done

**Comment by tenox7** [comment] 2019-06-08 00:42
I have opened an upstream issue https://github.com/chromedp/chromedp/issues/380

**Comment by tenox7** [comment] 2019-06-11 09:38
Please test this unofficial build. It works for me. If confirmed I will make a new official build. Thanks!

http://tnx3.tenox.net/get//wrp/wrp-linux-rpi-test 
and
http://tnx3.tenox.net/get//wrp/wrp-linux-test

**Comment by Gapstare** [comment] 2019-06-12 02:25
Hi there! :)
I've tested the new rpi version, it works great! when idle it doesn't even show up in ``top``. Top notch work.

**Comment by tenox7** [comment] 2019-06-12 20:48
Awesome, thank you for reporting and testing! Closing the bug.

**Closed by tenox7** 2019-06-12 20:48 UTC
Labels: bug
