### ISSUE TITLE
linux env

### ISSUE THREAD

**Issue by pouledodue** [tenox7/wrp#31] opened 2019-04-28 17:37 UTC
hi
I tried installing on some different linux versions and it always fails
Can you share on what distribution and version you installed it?
version of openssl also?

**Comment by Hubcapp** [comment] 2019-05-26 23:06
works for me on debian stretch. openssl 1.1.0j-1~deb9u1

**Comment by tenox7** [comment] 2019-05-26 23:49
Also please share the error message you are getting.

**Comment by tenox7** [comment] 2019-05-31 08:28
I'm closing this as unable to reproduce. Also GoLang version of WRP will have zero dependencies like that.

**Closed by tenox7** 2019-05-31 08:28 UTC
